In [1]:
import numpy as np

In [5]:
arr = np.random.rand(3,2)
arr.mean(axis=1)
arr.std(axis=1)
arr.var(axis=1)

array([0.00050197, 0.00936525, 0.00096753])

In [12]:
m,n = int(input("Enter m: ")),int(input("Enter n: "))

In [15]:

arr = np.ones((m,n))
arr.dtype
arr.reshape((n,m))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = [0,5,6,np.nan,0,np.nan,1,0]
arr = np.array(arr)

zero_indices = np.where(arr == 0)[0]
non_zero_indices = np.where((~np.isnan(arr)) & (arr != 0))[0]
nan_indices = np.asarray(np.isnan(arr)).nonzero()


(array([3, 5]),)

In [ ]:
array1 = np.random.randint(low=5,high=100,size=[4,4])
array2 = np.random.randint(low=5,high=100,size=[4,4])
array3 = np.random.randint(low=5,high=100,size=[4,4])

array4 = array2 - array3
array5 = array1 * 2

covar_1_4 = np.cov(array1,array4)
covar_1_5 = np.cov(array1,array5)

covar_1_4 = np.corrcoef(array1,array4)
covar_1_5 = np.corrcoef(array1,array5)


(8, 8)

In [ ]:
arr1 = np.random.rand(1,10).reshape(1,10)[0]
arr2 = np.random.random_sample((10,1)).reshape(1,10)[0]

sumation = arr1[:len(arr1)//2 + 1] + arr1[:len(arr1)//2 + 1]
product = arr1[:len(arr1)//2 + 1] * arr1[:len(arr1)//2 + 1]
sumation,product

In [92]:
arr = np.random.random(size=(10,10))
arr.nbytes

800

In [ ]:
arr = np.random.randint(low=10,high=100,size=(m,n))

def swap_rows(arr1: np.array,s1 :int,s2 :int) -> np.array:
    temp = arr1[s1].copy()
    arr1[s1] = arr1[s2]
    arr1[s2] = temp
    return arr1

# print(arr)
# swap_rows(arr,1,3)

def reverse_column(arr: np.array, pos: int) -> np.array:
    arr[:,1] = arr[::-1,1]
    return arr 

print(arr)
reverse_column(arr,1)
